-- =============================================
-- Social Network Database Setup
-- =============================================

-- Create database
CREATE DATABASE IF NOT EXISTS socialnet CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE socialnet;

-- Create account table
CREATE TABLE IF NOT EXISTS account (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    fullname VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================
-- Sample Data (password for all users: 123456)
-- Hash generated by password_hash('123456', PASSWORD_DEFAULT)
-- =============================================

INSERT INTO account (username, fullname, password, description) VALUES
('admin', 'Admin User', '$2y$10$YJHp0HlNY1QKPG8wUqLcie7cMb4NvzxqQf1MYFGZxVnBJ9IVSB9G', 'System administrator. Managing the Social Network platform.'),
('johndoe', 'John Doe', '$2y$10$YJHp0HlNY1QKPG8wUqLcie7cMb4NvzxqQf1MYFGZxVnBJ9IVSB9G', 'Hello! I am John. I love coding and building web applications.'),
('janedoe', 'Jane Doe', '$2y$10$YJHp0HlNY1QKPG8wUqLcie7cMb4NvzxqQf1MYFGZxVnBJ9IVSB9G', 'Hi there! I am Jane. Passionate about design and photography.');
